#!/usr/bin/env python3
import pathlib, pandas
SPATIAL_COVERAGE_DIR = pathlib.Path(__file__).parent.resolve()
import os

if "BILLING_PROJECT_ID" not in os.environ: raise Exception('Please set a BILLING_PROJECT_ID as an environment variable')

import basedosdados

tree = basedosdados.read_sql('''
    SELECT
    LOWER(CONCAT('sa.br.', sigla_uf, '.', id_municipio)) AS id,
    nome AS `label__pt`,
    nome AS `label__en`,
    FROM `basedosdados.br_bd_diretorios_brasil.municipio`

    UNION ALL

    SELECT
    LOWER(CONCAT('sa.br.', sigla)) AS id,
    nome AS `label__pt`,
    nome AS `label__en`,
    FROM `basedosdados.br_bd_diretorios_brasil.uf`

    UNION ALL

    SELECT
    LOWER(CONCAT(sigla_continente,'.',sigla_iso2)) AS id,
    nome_pt AS `label__pt`,
    nome_en AS `label__en`,
    FROM `basedosdados-dev.br_bd_diretorios_mundo.pais`

    UNION ALL

    SELECT
    LOWER(CONCAT(sigla)) AS id,
    nome_pt AS `label__pt`,
    nome_en AS `label__en`,
    FROM `basedosdados-dev.br_bd_diretorios_mundo.continente`

    ORDER BY id
''', billing_project_id=os.environ["BILLING_PROJECT_ID"])

path = SPATIAL_COVERAGE_DIR / 'spatial_coverage_tree.csv'
tree.to_csv(path, index=False)
print(f'{tree.shape[0]} lines saved to {path}')
print(f'Done')
