version: "3.5"
services:
  nginx:
    image: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    secrets:
      - fullchain
      - privkey
    ports:
      - 443:443
      - 80:80
    networks:
      - basedosdados
    # logging:
    #   driver: syslog
    #   options:
    #     syslog-address: tcp://logstash:5001
    #     syslog-facility: daemon

  ckan:
    networks:
      - basedosdados
    restart: always
    healthcheck:
      interval: 30s
      timeout: 5s
      start_period: 15s
      test: curl -f -k http://localhost:5000 || exit 1

    volumes:
      - ./assets:/app/uploads/

  next:
    command: ["yarn", "run", "production"]
    networks:
      - basedosdados

  strapi:
    networks:
      - basedosdados

  strapi-db:
    networks:
      - basedosdados

  solr:
    networks:
      - basedosdados
    restart: always
    volumes:
      - ./solr_data:/opt/solr/server/solr/ckan/data
  db:
    restart: always
    networks:
      - basedosdados
    volumes:
      - ./pg_data:/var/lib/postgresql/data
  redis:
    restart: always
    networks:
      - basedosdados
  autoheal:
    restart: always
    image: willfarrell/autoheal
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  basedosdados:
    name: basedosdados

secrets:
  fullchain:
    file: /etc/letsencrypt/live/basedosdados.org/fullchain.pem
  privkey:
    file: /etc/letsencrypt/live/basedosdados.org/privkey.pem
