# Generated by Django 4.0 on 2021-12-15 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_title', models.CharField(blank=True, max_length=30, verbose_name='Título do Menu')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Título da Página')),
                ('left_column_markdown', models.TextField(verbose_name='Texto Markdown da coluna da esquerda')),
                ('right_column_markdown', models.TextField(verbose_name='Texto Markdown da coluna da direita')),
                ('show_in_menu', models.BooleanField(default=False, verbose_name='Mostrar no menu?')),
            ],
            options={
                'verbose_name': 'Página',
                'verbose_name_plural': 'Páginas',
            },
        ),
    ]
