const getPeople ={
  "1100015": {
    "id": 1100015,
    "name": "Daniel Herrera",
    "description": "Graduado e Mestre em Economia pela Universidade Estadual de Campinas (Unicamp). Trabalha há 5 anos com finanças, modelagem econômica e regulação de concessões públicas.",
    "email": "daniel.herrera.pinto@gmail.com",
    "twitter": "",
    "github": "",
    "website": "",
    "linkedin": "daniel-herrera-27432959",
    "photo_url": "https://basedosdados-static.s3.us-east-2.amazonaws.com/equipe/daniel.png"
  },
  "1100023": {
    "id": 1100023,
    "name": "Fred Israel",
    "description": "Engenheiro de Software no Google.",
    "email": "fredisrael@gmail.com",
    "twitter": "",
    "github": "polvoazul",
    "website": "",
    "linkedin": "",
    "photo_url": "https://basedosdados-static.s3.us-east-2.amazonaws.com/equipe/fred.png"
  },
  "1100031": {
    "id": 1100031,
    "name": "Isabel Opice",
    "description": "Co-fundadora e Diretora de Operações da Impulso Gov, Mestre em Desenvolvimento Internacional pela Universidade de Harvard e em Economia pela Universidade de São Paulo, com experiência no Governo do Estado de São Paulo e no Instituto Ayrton Senna.",
    "email": "isabel@impulsogov.org",
    "twitter": "",
    "github": "",
    "website": "",
    "linkedin": "isabel-opice-126b037a",
    "photo_url": "https://basedosdados-static.s3.us-east-2.amazonaws.com/equipe/isabel.png"
  },
  "1100049": {
    "id": 1100049,
    "name": "Matheus Ávila",
    "description": "Gerente de Produtos na Clipboard Health, healthtec americana que virou unicórnio em Maio de 2022. Economista formado pela Unicamp em 2019. Apaixonado por dados, abraçou a BD para torná-la sustentável por meio de produtos e serviços que possam transformar o cenário de dados de instituições parceiras e clientes.",
    "email": "matheus.avila@basedosdados.org",
    "twitter": "",
    "github": "MathAvila-CBH",
    "website": "",
    "linkedin": "math-avila",
    "photo_url": "https://basedosdados-static.s3.us-east-2.amazonaws.com/equipe/matheus_avila.png"
  },
  "1100056": {
    "id": 1100056,
    "name": "Tomás Nóbrega",
    "description": "Doutorando em Economia pelo Insper com foco de pesquisa em finanças empíricas e estatística. É um apaixonado por dados e usuário recorrente da BD. Além disso, Tomás tem anos de experiência em gestão administrativa, financeira e contábil. Hoje usa isso para ajudar, participando do conselho fiscal.",
    "email": "tomasrn@al.insper.edu.br",
    "twitter": "",
    "github": "",
    "website": "",
    "linkedin": "tomasnobrega",
    "photo_url": "https://basedosdados-static.s3.us-east-2.amazonaws.com/equipe/tom%C3%A1s.png"
  },
  "1200807": {
    "id": 1200807,
    "name": "Kaline Santos",
    "description": "",
    "email": "",
    "twitter": "",
    "github": "kalinest",
    "website": "",
    "linkedin": "",
    "photo_url": ""
  },
  "2107308": {
    "id": 2107308,
    "name": "Fernanda Scovino",
    "description": "Cientista de Dados na Prefeitura do Rio de Janeiro.",
    "email": "fernanda.scovino@basedosdados.org",
    "twitter": "FernandaScovino",
    "github": "fernandascovino",
    "website": "",
    "linkedin": "fernanda-scovino",
    "photo_url": "https://basedosdados-static.s3.us-east-2.amazonaws.com/equipe/fernanda.png"
  },
  "2302206": {
    "id": 2302206,
    "name": "Aldemir Lucas",
    "description": "Desenvolvedor Front-End atuando na criação de novas funcionalidades e melhorando a experiência no site da BD. Desenvolvendo uma aplicação responsiva, com uma variedade de experiências que engajam e contribuem na jornada de nossos usuários.",
    "email": "aldemirlucas@basedosdados.org",
    "twitter": "",
    "github": "AldemirLucas",
    "website": "",
    "linkedin": "aldemirlucas",
    "photo_url": "https://basedosdados-static.s3.us-east-2.amazonaws.com/equipe/aldemir.png"
  },
  "2308708": {
    "id": 2308708,
    "name": "Ingrid Rabelo",
    "description": "Mestranda em Economia Aplicada pela Universidade Federal de Pernambuco. Na BD, suas atividades incluem extração e limpeza de dados, além de análises e geração de visualizações na área de educação.",
    "email": "ingrid.rabelo@basedosdados.org",
    "twitter": "IngridSRabelo",
    "github": "IngridSRabelo",
    "website": "",
    "linkedin": "ingrid-de-sales-rabelo",
    "photo_url": "https://basedosdados-static.s3.us-east-2.amazonaws.com/equipe/ingrid.png"
  },
  "2412559": {
    "id": 2412559,
    "name": "Cristina de Albuquerque",
    "description": "Administradora.",
    "email": "administrativo@basedosdados.org",
    "twitter": "",
    "github": "",
    "website": "",
    "linkedin": "",
    "photo_url": "https://basedosdados-static.s3.us-east-2.amazonaws.com/equipe/cristina.png"
  },
  "2707602": {
    "id": 2707602,
    "name": "Gustavo Alcântara",
    "description": "Geógrafo pela PUC-Campinas e mestrando em Demografia pela Unicamp. Na BD, se dedica a ETL dos dados, análises e visualizações para subsidiar insights gerais.",
    "email": "gustavo.alcantara@basedosdados.org",
    "twitter": "Alcantara_gus_",
    "github": "gustavoalcantara",
    "website": "",
    "linkedin": "gustavoalcantarageografia",
    "photo_url": "https://basedosdados-static.s3.us-east-2.amazonaws.com/equipe/gustavo.png"
  },
  "2903201": {
    "id": 2903201,
    "name": "Fabio Vasconcellos",
    "description": "Doutor em Ciência Política pelo Instituto de Estudos Sociais e Políticos (IESP/UERJ) e Mestre em Comunicação Social pela UERJ.  Responsável por coordenar e captar projetos da BD com parceiros externos. É também  professor da ESPM e da UERJ e tem interesse em pesquisa em temas como Jornalismo de Dados, Análise de Dados, Comportamento Eleitoral e Pesquisas Eleitorais.",
    "email": "fabio.vasconcellos@basedosdados.org",
    "twitter": "fvas",
    "github": "",
    "website": "https://fabiovasconcellos10.wordpress.com/",
    "linkedin": "f%C3%A1bio-vasconcellos-39aabb96",
    "photo_url": "https://basedosdados-static.s3.us-east-2.amazonaws.com/equipe/f%C3%A1bio.png"
  },
  "2919306": {
    "id": 2919306,
    "name": "Ricardo Dahis",
    "description": "Pesquisador na PUC-Rio e doutor em Economia pela Northwestern University, Ricardo lidera projetos nas áreas de economia política, meio ambiente, e economia aplicada. Atua na interseção entre academia, setor público e ciência de dados em busca de impacto em escala.",
    "email": "rdahis@basedosdados.org",
    "twitter": "rdahis",
    "github": "rdahis",
    "website": "www.ricardodahis.com",
    "linkedin": "rdahis",
    "photo_url": "https://basedosdados-static.s3.us-east-2.amazonaws.com/equipe/ricardo.png"
  },
  "2919702": {
    "id": 2919702,
    "name": "Crislane Alves",
    "description": "Graduanda em Economia e Matemática pela Universidade Estadual do Sudoeste da Bahia. Pesquisadora no Grupo de Pesquisa em Economia, Meio Ambiente e Inovação (GREMI) e economista júnior no Pacto de Promoção da Equidade Racial. Na BD, é responsável pela área de Dados.",
    "email": "crislanealves@basedosdados.org",
    "twitter": "crislane_alves",
    "github": "",
    "website": "",
    "linkedin": "s-alvescrislane",
    "photo_url": "https://basedosdados-static.s3.us-east-2.amazonaws.com/equipe/crislane.png"
  },
  "3101201": {
    "id": 3101201,
    "name": "Isadora Bugarin",
    "description": "",
    "email": "",
    "twitter": "",
    "github": "",
    "website": "",
    "linkedin": "",
    "photo_url": ""
  },
  "3146107": {
    "id": 3146107,
    "name": "Ângela Jardim",
    "description": "Organizada por natureza e apaixonada por pessoas, encontrou no backoffice sua forma de servir em sintonia com o que é.",
    "email": "administrativo@basedosdados.org",
    "twitter": "",
    "github": "",
    "website": "",
    "linkedin": "",
    "photo_url": "https://basedosdados-static.s3.us-east-2.amazonaws.com/equipe/sem_foto.png"
  },
  "3306305": {
    "id": 3306305,
    "name": "Lucas Moreira",
    "description": "Bacharel em Economia pela Universidade Federal de Juiz de Fora e assistente de pesquisa no Banco Mundial. Aqui na BD, se dedica principalmente aos dados de educação.",
    "email": "lucas.moreira@basedosdados.org",
    "twitter": "lucasnasc_m",
    "github": "lucasnascm",
    "website": "",
    "linkedin": "moreiranlucas",
    "photo_url": "https://basedosdados-static.s3.us-east-2.amazonaws.com/equipe/lucas.png"
  },
  "3504008": {
    "id": 3504008,
    "name": "Diego Oliveira",
    "description": "Físico pela Unicamp e engenheiro de dados no Escritório de Dados da Prefeitura do Rio de Janeiro. Responsável pela arquitetura e manutenção do DataLake da prefeitura e da BD, mantenedor do pacote basedosdados em python.",
    "email": "dsoliveira@basedosdados.org",
    "twitter": "",
    "github": "d116626",
    "website": "",
    "linkedin": "diego-oliveira-4477519b",
    "photo_url": "https://basedosdados-static.s3.us-east-2.amazonaws.com/equipe/diego.png"
  },
  "3509502": {
    "id": 3509502,
    "name": "Giovane Caruso",
    "description": "Profissional de marketing digital e redação publicitária, responsável pelo planejamento e criação de conteúdo das redes sociais da BD, além da gestão da nossa equipe de comunicação.",
    "email": "giovane.caruso@basedosdados.org",
    "twitter": "CarusoGiovane",
    "github": "",
    "website": "",
    "linkedin": "giovane-carvalho-caruso-46514510a",
    "photo_url": "https://basedosdados-static.s3.us-east-2.amazonaws.com/equipe/giovane.png"
  },
  "3526001": {
    "id": 3526001,
    "name": "João Carabetta",
    "description": "Chefe Executivo de Dados da Prefeitura do Rio de Janeiro, Físico pela Unicamp e Mestre em Modelagem Matemática pela FGV, João atua na intersecção entre ciência de dados e governo.",
    "email": "joao.carabetta@basedosdados.org",
    "twitter": "JoaoCarabetta",
    "github": "JoaoCarabetta",
    "website": "",
    "linkedin": "JoaoCarabetta",
    "photo_url": "https://basedosdados-static.s3.us-east-2.amazonaws.com/equipe/joao.png"
  },
  "3548906": {
    "id": 3548906,
    "name": "Lucas Rodrigues",
    "description": "Economista. Responsável pela área de infraestrutura da BD, atuando diretamente na construção de ETLs,  pipelines de dados e manutenção dos pacotes, além de supervisionar e prover suporte técnico a analistas da organização.",
    "email": "lucas.rodrigues@basedosdados.org",
    "twitter": "",
    "github": "lucascr91",
    "website": "",
    "linkedin": "lucas-cavalcanti-rodrigues-4b3b9514b",
    "photo_url": "https://basedosdados-static.s3.us-east-2.amazonaws.com/equipe/lucas_rodrigues.png"
  },
  "3554003": {
    "id": 3554003,
    "name": "Nayara Moraes",
    "description": "Bacharela em Relações Internacionais pela Universidade de São Paulo. Como boa generalista, atuou em diferentes campos da comunicação em projetos sociais. Na BD, trabalha com branding e design de produtos digitais.",
    "email": "nayaramoraes@basedosdados.org",
    "twitter": "",
    "github": "nayaramrsc",
    "website": "",
    "linkedin": "nayaramoraesdacosta",
    "photo_url": "https://basedosdados-static.s3.us-east-2.amazonaws.com/equipe/nayara.png"
  },
  "4101804": {
    "id": 4101804,
    "name": "Laura Amaral",
    "description": "Engenheira Biomédica pela Universidade Federal do ABC. Na BD é responsável pela equipe de dados",
    "email": "laura.amaral@basedosdados.org",
    "twitter": "",
    "github": "laura-l-amaral",
    "website": "",
    "linkedin": "laura-amaral-574b73121",
    "photo_url": "https://basedosdados-static.s3.us-east-2.amazonaws.com/equipe/laura.png"
  },
  "4115606": {
    "id": 4115606,
    "name": "Matheus Valentim",
    "description": "Auxiliar de pesca na Dinamarca. Abraça árvores e canta para passarinhos dormir no tempo livre. Fã da Dua Lipa e banda do Serginho Groisman (Skank).",
    "email": "",
    "twitter": "mvalentimk",
    "github": "mavalentim",
    "website": "",
    "linkedin": "",
    "photo_url": ""
  },
  "4300455": {
    "id": 4300455,
    "name": "Guilherme Alves",
    "description": "Entusiasta em defesa cibernética, infraestrutura como código e tecnologia em geral. Vem trabalhando nos últimos anos com Docker, Python, ECS e iniciando em Kubernetes.",
    "email": "guilherme.alves@basedosdados.org",
    "twitter": "",
    "github": "guialvesp1",
    "website": "",
    "linkedin": "guialvesp1",
    "photo_url": "https://basedosdados-static.s3.us-east-2.amazonaws.com/equipe/guilherme.png"
  },
  "5103304": {
    "id": 5103304,
    "name": "Caio R",
    "description": "",
    "email": "",
    "twitter": "",
    "github": "",
    "website": "",
    "linkedin": "",
    "photo_url": ""
  },
  "5103437": {
    "id": 5103437,
    "name": "Breno Gomes",
    "description": "",
    "email": "",
    "twitter": "",
    "github": "",
    "website": "",
    "linkedin": "",
    "photo_url": ""
  },
  "5103700": {
    "id": 5103700,
    "name": "Hevilyn Souza",
    "description": "Graduanda em Economia na PUC-Rio. Torce para o Flamengo, todos os dias.",
    "email": "",
    "twitter": "@hevsouzaa",
    "github": "hevsouza",
    "website": "",
    "linkedin": "Hevilyn-souza",
    "photo_url": ""
  }
}

export default getPeople