name: CI

on:
  push:
    branches:
      - nextjs

jobs:
  build-container:
    if: github.ref_name == 'nextjs'
    name: Build and publish container image
    runs-on: ubuntu-latest
    environment:
      name: development
    env:
      NEXT_PORT: ${{ vars.NEXT_PORT }}
      NEXT_PUBLIC_API_URL: ${{ vars.NEXT_PUBLIC_API_URL }}
      NEXT_PUBLIC_SITE_NAME: ${{ vars.NEXT_PUBLIC_SITE_NAME }}
      NODE_ENV: ${{ vars.NODE_ENV }}
      IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:development

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: nextjs

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: nextjs
          file: nextjs/Dockerfile
          push: true
          tags: ${{ env.IMAGE_NAME }}
