name: CI-DEV
on:
  push:
    branches: [develop]
jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Clone repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Add secret files
        env:
          DOT_ENV_PROD: ${{ secrets.DOT_ENV_PROD }}
          PROD_CKAN_INI: ${{ secrets.PROD_CKAN_INI }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: 'echo "$DOT_ENV_PROD" > .env.prod && echo "$PROD_CKAN_INI" > ./configs/ckan.override.prod.ini && mkdir ~/.ssh && echo "$SSH_KEY" > ~/.ssh/BD.pem && chmod 700 ~/.ssh ~/.ssh/BD.pem'
      - name: Deploy script
        run: ./deploy_staging.sh deploy
      - name: Report Failures
        if: "${{ failure() }}"
        uses: cstuder/apprise-ga@master
        env:
          APPRISE_URL: "${{ secrets.APPRISE_NOTIFICATION_URL }}"
          INFRA_HANDLES: "${{secrets.NOTIFICATION_DISCORD_INFRA_HANDLES}}" # not working, debug this
        with:
          title: "Broken CI"
          message: "<#809077231611674685>. CI DEPLOY FAILED, please check https://github.com/basedosdados/website/actions"
